Namanl2001/MERN-Gurujii-dev

- README.md
> Doc fixes nikita

- contributing.md
Reference to issue #16 . Added contributing.md
> Add Contributing.md

- README.md
Added Concurrently Dependency to Project
Closes: open PR
Added Concurrently Dependency
NA
> Added Concurrently Dependency to Project

- README.md
fixes #5 
Closes: #[issue number that will be closed through this PR]
> Added Website Gif

- src/App.css
> Added Pointer Cursor Property for Dropdown items

- src/components/home.jsx
https://github.com/Namanl2001/MERN-Gurujii-dev/issues/9 
Closes: #9 
Generate data that is random from the data that we get from Backend
> Randomizatin add to the Profile

- README.md
- public/index.html
- src/components/navbar.jsx
- src/components/style.css
- UI of delete Profile
Closes: #41
> Dialog box delete

- .prettierignore
- .prettierrc.json
- package.json
- src/App.css
- src/App.js
- src/components/card.jsx
- src/components/filter.jsx
- src/components/form.jsx
- src/components/home.jsx
- src/components/login.jsx
- src/components/logout.jsx
- src/components/navbar.jsx
- src/components/scrollToTop.jsx
- src/components/style.css
- src/components/update.jsx
- src/index.css
- src/index.js
- src/store/reducer/user.js
- yarn.lock
- This PR will close the issue #67
Closes: #[67]
Just added some configuration to auto-format the code using prettier whenever a commit is made.
NA
> RE: Auto Format Code Issue #67 Fix #68

- backend/server.js
Closes: #70
I have uninstall the dependency body-parser and made changes to following lines in server.js
1. remove -> const bodyParser = require('body-parser');
2. app.use(bodyParser.urlencoded({ extended: false })); -> is replaced with -> app.use(express.urlencoded({ extended: false}));
NA
> body-parser removed and changes made to server.js

- backend/package-lock.json
- backend/package.json
- backend/server.js
- backend/yarn.lock
Added helmet for security http headers.
Added rate limiter to receive 100 requests per hour from a particular IP address.
Added mongo sanitize for data sanitization against noSQL query injection
Added xss for data sanitization against XSS.
Please review and if any changes required let me know.
Thank you.
For issue #76
> Added various security features issue #76

- src/App.js
- src/components/Footer.js
- src/components/style.css
Closes: #[issue number that will be closed through this PR]
I have added a footer.js file and some styling in styles.css I imported the same in the app.js file
NA
- [x ] My code follows the guidelines of this project.
I don't use .jsx files too often so I used the .js file and added the changes accordingly....
> added footer

- src/components/form.jsx
- src/components/update.jsx
> removes default value on expanding any dropdown

- src/components/chatbot.jsx
added sir/madam in chatbox
Closes: #115
> added sir/madam in chatbox. Fixes #115

- src/App.css
- src/components/card.jsx
Closes: #[issue number that will be closed through this PR]
> new flip cards

- src/components/form.jsx
- src/components/update.jsx
Ms. option in teacher's profile form was missing
Closes: #105 
I added Ms. option in create  & update profile form.
> Ms. option added

- .github/workflows/issue_label.yml
Closes: #119 
Added a script that can auto-label issues with the GSSOC21 label whenever contributors ask to work under that label.
None
Please merge my request and assign me a GSSOC tag and a level tag.
> Auto Labelling Bot

- src/components/card.jsx
- src/components/style.css
Closes: #[issue number that will be closed through this PR]
> flip card changes made

- README.md
- backend/server.js
Closes: #144 
Removed deprecated code
No
> Removed body-parser

- src/components/home.jsx
Closes: #101 
Used bootstrap4-react Animated progress component
NA
Mobile
PC
> Added loading bar

- src/components/E404.jsx
- src/components/home.jsx
- src/components/navbar.jsx
- src/components/style.css
Navbar is fixed at top as when  you scroll down it will remain intact .
Closes: #31 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Enhancement in the existing features
- [ x] Other
NA
- [x ] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [ x] My changes generate no new warnings.
- [ x] I have verified/tested my code by running it locally.
https://user-images.githubusercontent.com/67833077/116518245-a1c9bb00-a8ed-11eb-91b3-946d947e34ae. …
> Header is fixed

- src/components/form.jsx
- src/components/update.jsx
https://user-images.githubusercontent.com/68965499/116811800-e8771980-ab68-11eb-981f-b595611f6a8d.mp4
@Namanl2001 @sagar-barapatre please review this pr.
> form validation

- src/components/E404.jsx
- src/components/style.css
Closes: #170 
Also, there was an warning in style.css related to float position, i had fixed that warning
NA
> Enhancement Done!

- package.json
- src/components/filter.jsx
- src/store/reducer/user.js
- yarn.lock
Closes: #111
I have just added a new 'tutor' state in the reducer and I am manipulating it in accordance with other filters as required.
NA
Please tag @akshay1027 along with me in this PR
> Added home/external tutor filter

- src/App.css
Closes: #190 
@Namanl2001 please review this pr.
> scroll bar

- src/App.js
- src/components/Preloader.jsx
- src/components/style.css
Closes: #132 
@Namanl2001 please have a look at this pr .
> splash screen

- package.json
- src/components/home.jsx
- src/components/style.css
- yarn.lock
Closes: #194 
https://user-images.githubusercontent.com/68965499/118446328-23eb1980-b70d-11eb-9b3a-ce15984b1b08.mp4
@Namanl2001 please have a look at this pr.
> social media sidebar added

- backend/controllers/user.controller.js
- backend/middleware/admin.js
- backend/models/user.model.js
- package.json
- yarn.lock
> added admin middleware

- src/components/alert.jsx
…isplayed
Closes: #201
Moved timer to outside of component return. After 10 seconds, this.state.hidden is set to false in alert.jsx, but timer is not displayed. 
> Remove alert timeout timer from UI

- src/components/chatbot.jsx
Fixed #206.
Closes: #[206]
Added speech recognition and speech synthesis feature in chatbot.
NA
> Speech Feature In ChatBot

- backend/controllers/admin.controller.js
- backend/routes/admin.js
- backend/server.js
- package.json
- yarn.lock
1) admin can fetch all the users
2)admin can fetch a particular user by its Id
Closes: #204 
> admin feature added

- backend/controllers/user.controller.js
- backend/models/user.model.js
> fixed update profile

- .github/workflows/automessege_on_pr.yml
@Namanl2001 please review this pr.
> auto messege on pr

- backend/controllers/admin.controller.js
- backend/routes/admin.js
> Admin : delete/update user
